apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot
        role: master
        tier: backend
    spec:
      containers:
      - name: springbootpruebaborja
        image: borjaortizllamas/springbootcrudbaborja:1.0.0
        ports:
        - containerPort: 8080
          protocol: TCP